### ISSUE TITLE
Update page header and add "back" button

### ISSUE THREAD

**Issue by Letsgohyde** [cmu-delphi/forecast-eval#110]
- [x] Update page header styling
- [x] add back button

<img width="1220" alt="Screen Shot 2021-04-23 at 2 28 24 PM" src="https://user-images.githubusercontent.com/7318770/115943653-00aeb080-a466-11eb-9b40-5663c42a475f.png">
Link to figma mocks: https://www.figma.com/file/IiYu74VmEi4GVS4bnYaTd6/Delphi-Site-Redesign-Current?node-id=2696%3A71258

**Comment by kateharwood** [comment]
Done
