### ISSUE TITLE
Create "Export scores" tab

### ISSUE THREAD

**Issue by jacobbien** [cmu-delphi/forecast-eval#117]
(This is inspired by the very nice "Export Data" page on covidcast: https://delphi.cmu.edu/covidcast/export/)

- User selects some forecasters, aheads, scores, and a time window.
- Provides user with a "Download CSV" or R code snippet that can be copied and pasted.
- What is returned is a data frame with columns `geo_value`, `forecast_date`, `target_end_date`, `ahead`, and then whatever scores have already been calculated (such as `weighted_interval_score`, `coverageXX`, `absolute_error`... i.e., whatever has already been computed on the backend, pre-aggregation).

**Motivation:** This will allow power users to make all the aggregates they want without having to go through the slow process of downloading all the individual forecasts and computing scores themselves.

**Comment by kateharwood** [comment]
Done, in staging currently.
