### ISSUE TITLE
Configured docker image web-hook

### ISSUE THREAD

**Issue by tildechris** [cmu-delphi/forecast-eval#14]
In order to configure automatic deployment of the dashboard on the dev and main branches, we'll need to send a webhook event after the new images are built.

You can take a look at how @sgratzl set this up in www-main: https://github.com/cmu-delphi/www-main/blob/3af6b979499421bcf158b8d1a06da3c9b05d0aa8/.github/workflows/ci_fast.yaml#L47

Note that instead of doing this after every commit on a PR, we should probably set up a similar system where we only build files after merges into dev or main are complete.

**Comment by kateharwood** [comment]
Done
