### ISSUE TITLE
Show Forecasters' Prediction button not shown on load

### ISSUE THREAD

**Issue by ryantibs** [cmu-delphi/forecast-eval#186]
The Show Forecasters' Predictions button is not shown on page load, which is kind of confusing (this came up with a user today). 

(Actually it does appear to me for a very brief moment on page load, and then it gets hidden again!)

It only comes up when an As Of date is selected.  But we should have it shown at all times and simply grayed out if it is not applicable for a particular As Of date.

**Comment by nmdefries** [comment]
The way this is currently implemented, the `showForecasts` selection is saved even if the checkbox was hidden (e.g. switching from as-of data to current data). The previous selection is restored if the user revisits any as-of data.

In the test implementation of the graying-out feature, the checkbox is grayed out with the checkbox still showing the saved selection. This could be confusing. I'm wondering if you have any preferences on this @ryantibs.
