### ISSUE TITLE
Docker build errors

### ISSUE THREAD

**Issue by dsweber2** [cmu-delphi/forecast-eval#287]
Trying to use make to get a docker version of this running, and I ran into a couple of problems:
1. `imageTag` isn't defined anywhere; defining it as `imageTag=latest` at the start of the makefile was a work around, but I assume that it should generally be added to environmental variables instead
2. getting a 100 error from `apt-get`(?) inside of docker:
```
E: Problem executing scripts APT::Update::Post-Invoke 'rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin || true'
E: Sub-process returned an error code
The command '/bin/sh -c apt-get update && apt-get install -qq -y     libgdal-dev     libudunits2-dev &&     rm -rf /var/cache/apt &&     apt-get clean' returned a non-zero code: 100
make: *** [Makefile:72: build_dashboard] Error 100
```
which appears to not be the problem described in the readme

**Comment by nmdefries** [comment]
> getting a 100 error from apt-get(?) inside of docker

Do you have an old version of docker? Might try updating to [`Docker >= 20.10.9`](https://stackoverflow.com/questions/71941032/why-i-cannot-run-apt-update-inside-a-fresh-ubuntu22-04) as a first step.
