### ISSUE TITLE
Check whether data update is necessary on new app session

### ISSUE THREAD

**Issue by kateharwood** [cmu-delphi/forecast-eval#97]
Currently the app pulls down the data from AWS each time a user loads the page. This keeps the data up to date, but means that the page takes a long time to load.

We can add a global variable to the app to hold the freshness date / hash of the current AWS data, and on each new user session, make a call to the AWS bucket to check whether the date / hash (whatever identifying info AWS provides) has changed, and only fetch the data if it has (then update the global variable).

**Comment by nmdefries** [comment]
Closed by #169.
